AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - bin/**/*
    - node_modules/**/*
    - public/**/*
    - vendor/**/*
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
 Metrics/AbcSize:
  Enabled: false